//get
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";

export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";

export const GET_COMEDY_MOVIES = "GET_COMEDY_MOVIES";

export const GET_NOW_PLAYINGS = "GET_NOW_PLAYINGS";

export const GET_SEARCH_MOVIE = "GET_SEARCH_MOVIE";
//set
export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
